name: "Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution!  
        Please check existing feature requests before submitting.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Briefly describe the new feature or enhancement
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use case
      description: Why is this feature needed? Who benefits?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed implementation (optional)
      description: Suggestions on how this feature could be implemented
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
      description: Other solutions or workarounds tried
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context (optional)
      description: Any references, links, or discussions
    validations:
      required: false